
import { Outfit } from 'next/font/google';
import "./globals.css";

import ThemeProvider from "./provider/ThemeProvider";
import { AuthProvider } from "./context/AuthContext";
import SessionAuthProvider from "./provider/SessionProvider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${outfit.className} bg-neutral-950`}>
        <SessionAuthProvider>
        <AuthProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </AuthProvider>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
