import {  Jost } from "next/font/google";
import "./globals.css";

import ThemeProvider from "./provider/ThemeProvider";
import { AuthProvider } from "./context/AuthContext";
import AuthUserProvider from "./provider/AuthProvider";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={jost.className}>
        <AuthProvider>
        <AuthUserProvider>
            <ThemeProvider>
               {children}  
            </ThemeProvider>      
        </AuthUserProvider>
        </AuthProvider>
          

      </body>
    </html>
  );
}
